#sivaprakash44/appserver:v1
FROM  tomcat
ADD   https://s3-us-west-2.amazonaws.com/studentapi-cit/student.war webapps/student.war
ADD   https://s3-us-west-2.amazonaws.com/studentapi-cit/mysql-connector.jar lib/mysql-connector.jar
ADD   context.xml conf/context.xml