version: '3'
services:
  httpd:
    build: webserver/.
    ports:
      - "80:80"
  tomcat:
    build: appserver/.
    ports:
      - "8080:8080"
  dbsetup:
    build: db-setup/.   
  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root

