#sivaprakash44/httpd:v3
FROM  centos
RUN  yum install httpd  -y
EXPOSE 80
ADD https://s3-us-west-2.amazonaws.com/studentapi-cit/index.html /var/www/html/index.html
RUN chown apache:apache /var/www/html/index.html
CMD  httpd -DFOREGROUND